namespace Ransys.Domain;

// Strongly typed identifiers (Canonical Data Model §99).
// Values are generated by RANSYS (UUIDv7 recommended, ERD v1.1 §5); an empty GUID is a programming error.

public readonly record struct TransactionId
{
    public TransactionId(Guid value) => Value = IdGuard.NotEmpty(value, nameof(TransactionId));

    public Guid Value { get; }

    public override string ToString() => Value.ToString("D");
}

public readonly record struct MerchantId
{
    public MerchantId(Guid value) => Value = IdGuard.NotEmpty(value, nameof(MerchantId));

    public Guid Value { get; }

    public override string ToString() => Value.ToString("D");
}

public readonly record struct ChannelId
{
    public ChannelId(Guid value) => Value = IdGuard.NotEmpty(value, nameof(ChannelId));

    public Guid Value { get; }

    public override string ToString() => Value.ToString("D");
}

public readonly record struct ProductId
{
    public ProductId(Guid value) => Value = IdGuard.NotEmpty(value, nameof(ProductId));

    public Guid Value { get; }

    public override string ToString() => Value.ToString("D");
}

public readonly record struct ProviderId
{
    public ProviderId(Guid value) => Value = IdGuard.NotEmpty(value, nameof(ProviderId));

    public Guid Value { get; }

    public override string ToString() => Value.ToString("D");
}

public readonly record struct WalletId
{
    public WalletId(Guid value) => Value = IdGuard.NotEmpty(value, nameof(WalletId));

    public Guid Value { get; }

    public override string ToString() => Value.ToString("D");
}

public readonly record struct AttemptId
{
    public AttemptId(Guid value) => Value = IdGuard.NotEmpty(value, nameof(AttemptId));

    public Guid Value { get; }

    public override string ToString() => Value.ToString("D");
}

internal static class IdGuard
{
    public static Guid NotEmpty(Guid value, string idName) =>
        value == Guid.Empty
            ? throw new ArgumentException($"{idName} cannot be an empty GUID.", nameof(value))
            : value;
}
