<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/Ransys.Api/Ransys.Api.csproj" />
    <ProjectReference Include="../Ransys.Testing.PostgreSql/Ransys.Testing.PostgreSql.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi.YamlReader" />
  </ItemGroup>

</Project>
