<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/Ransys.TransactionCore/Ransys.TransactionCore.csproj" />
    <ProjectReference Include="../../src/Ransys.Persistence.PostgreSql/Ransys.Persistence.PostgreSql.csproj" />
    <ProjectReference Include="../../src/Ransys.Infrastructure/Ransys.Infrastructure.csproj" />
    <ProjectReference Include="../Ransys.Testing.PostgreSql/Ransys.Testing.PostgreSql.csproj" />
  </ItemGroup>

</Project>
