-- RANSYS PostgreSQL Reference DDL v1.1
-- Engineering baseline, not yet production migration package.
-- UUID values are expected to be generated by the application (recommended UUIDv7).

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS ledger;
CREATE SCHEMA IF NOT EXISTS integration;
CREATE SCHEMA IF NOT EXISTS config;
CREATE SCHEMA IF NOT EXISTS async;

-- =========================================================
-- CORE MASTER
-- =========================================================

CREATE TABLE core.merchants (
    merchant_id uuid PRIMARY KEY,
    merchant_code varchar(64) NOT NULL UNIQUE,
    merchant_name varchar(200) NOT NULL,
    status varchar(32) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT ck_merchants_status
      CHECK (status IN ('ACTIVE','INACTIVE','SUSPENDED'))
);

CREATE TABLE core.channels (
    channel_id uuid PRIMARY KEY,
    merchant_id uuid NOT NULL REFERENCES core.merchants(merchant_id),
    channel_code varchar(64) NOT NULL,
    channel_type varchar(32) NOT NULL,
    auth_profile varchar(64) NOT NULL,
    status varchar(32) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT uq_channels_merchant_code UNIQUE (merchant_id, channel_code),
    CONSTRAINT ck_channels_status CHECK (status IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE core.products (
    product_id uuid PRIMARY KEY,
    product_code varchar(64) NOT NULL UNIQUE,
    product_name varchar(200) NOT NULL,
    category varchar(64) NOT NULL,
    status varchar(32) NOT NULL,
    metadata_schema jsonb NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE core.currency_definitions (
    currency_definition_id uuid PRIMARY KEY,
    currency_code char(3) NOT NULL,
    version_no integer NOT NULL,
    scale smallint NOT NULL,
    conversion_ratio numeric(30,12) NULL,
    effective_from timestamptz NOT NULL,
    effective_until timestamptz NULL,
    status varchar(32) NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT uq_currency_definition UNIQUE (currency_code, version_no),
    CONSTRAINT ck_currency_scale CHECK (scale BETWEEN 0 AND 8),
    CONSTRAINT ck_currency_status CHECK (status IN ('ACTIVE','SCHEDULED','EXPIRED')),
    CONSTRAINT ck_currency_effective_range
      CHECK (effective_until IS NULL OR effective_until > effective_from)
);

-- =========================================================
-- PROVIDER MASTER (created before transactions due FK)
-- =========================================================

CREATE TABLE integration.providers (
    provider_id uuid PRIMARY KEY,
    provider_code varchar(64) NOT NULL UNIQUE,
    provider_name varchar(200) NOT NULL,
    provider_type varchar(64) NOT NULL,
    adapter_service_name varchar(128) NOT NULL,
    protocol_type varchar(32) NOT NULL,
    status varchar(32) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT ck_provider_status CHECK (status IN ('ACTIVE','INACTIVE'))
);

-- =========================================================
-- CONFIG VERSION
-- =========================================================

CREATE TABLE config.config_versions (
    config_version_id uuid PRIMARY KEY,
    config_domain varchar(64) NOT NULL,
    version_no bigint NOT NULL,
    status varchar(32) NOT NULL,
    effective_from timestamptz NULL,
    effective_until timestamptz NULL,
    created_by uuid NOT NULL,
    approved_by uuid NULL,
    created_at timestamptz NOT NULL,
    approved_at timestamptz NULL,
    activated_at timestamptz NULL,
    CONSTRAINT uq_config_domain_version UNIQUE (config_domain, version_no),
    CONSTRAINT ck_config_status
      CHECK (status IN ('DRAFT','PENDING_APPROVAL','APPROVED','SCHEDULED','ACTIVE','EXPIRED')),
    CONSTRAINT ck_config_effective_range
      CHECK (effective_until IS NULL OR effective_from IS NULL OR effective_until > effective_from)
);

-- =========================================================
-- TRANSACTIONS
-- =========================================================

CREATE TABLE core.transactions (
    ransys_transaction_id uuid PRIMARY KEY,
    merchant_id uuid NOT NULL REFERENCES core.merchants(merchant_id),
    channel_id uuid NOT NULL REFERENCES core.channels(channel_id),
    product_id uuid NOT NULL REFERENCES core.products(product_id),
    transaction_type varchar(32) NOT NULL,

    client_reference varchar(128) NOT NULL,
    idempotency_key varchar(128) NULL,
    transaction_fingerprint varchar(128) NOT NULL,
    original_transaction_id uuid NULL REFERENCES core.transactions(ransys_transaction_id),

    amount numeric(30,8) NOT NULL,
    currency_definition_id uuid NOT NULL REFERENCES core.currency_definitions(currency_definition_id),
    merchant_charge_amount numeric(30,8) NOT NULL DEFAULT 0,
    total_reserve_amount numeric(30,8) NOT NULL DEFAULT 0,

    processing_status varchar(32) NOT NULL,
    financial_status varchar(32) NOT NULL,
    reconciliation_status varchar(32) NOT NULL,
    settlement_status varchar(32) NOT NULL,

    ransys_response_code char(4) NULL,
    reason_code varchar(64) NULL,
    reason_description varchar(500) NULL,

    initial_selected_provider_id uuid NULL REFERENCES integration.providers(provider_id),
    actual_provider_id uuid NULL REFERENCES integration.providers(provider_id),

    config_version_id uuid NULL REFERENCES config.config_versions(config_version_id),
    routing_config_version_id uuid NULL REFERENCES config.config_versions(config_version_id),
    fee_config_version_id uuid NULL REFERENCES config.config_versions(config_version_id),
    provider_policy_version bigint NULL,

    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

    received_at timestamptz NOT NULL,
    validated_at timestamptz NULL,
    financial_posted_at timestamptz NULL,
    completed_at timestamptz NULL,
    updated_at timestamptz NOT NULL,

    row_version bigint NOT NULL DEFAULT 1,

    CONSTRAINT ck_tx_amount CHECK (amount >= 0),
    CONSTRAINT ck_tx_merchant_charge CHECK (merchant_charge_amount >= 0),
    CONSTRAINT ck_tx_total_reserve CHECK (total_reserve_amount >= 0),
    CONSTRAINT ck_tx_row_version CHECK (row_version > 0),

    CONSTRAINT ck_tx_processing_status CHECK (
      processing_status IN (
        'RECEIVED','VALIDATED','PROCESSING','PENDING','IN_DOUBT',
        'SUCCESS','FAILED','REVERSAL_PENDING','REVERSED',
        'REFUND_PENDING','PARTIALLY_REFUNDED','REFUNDED'
      )
    ),
    CONSTRAINT ck_tx_financial_status CHECK (
      financial_status IN (
        'NONE','RESERVED','POSTED','RELEASED','REVERSAL_PENDING',
        'REVERSED','REFUND_PENDING','PARTIALLY_REFUNDED','REFUNDED','ADJUSTED'
      )
    ),
    CONSTRAINT ck_tx_recon_status CHECK (
      reconciliation_status IN ('UNMATCHED','PENDING','MATCHED','EXCEPTION','RESOLVED')
    ),
    CONSTRAINT ck_tx_settlement_status CHECK (
      settlement_status IN (
        'NOT_APPLICABLE','PENDING','INCLUDED','APPROVED',
        'READY_TO_PAY','SETTLED','ADJUSTED'
      )
    )
);

CREATE INDEX ix_transactions_merchant_received
    ON core.transactions(merchant_id, received_at DESC);

CREATE INDEX ix_transactions_channel_reference
    ON core.transactions(channel_id, client_reference);

CREATE INDEX ix_transactions_product_received
    ON core.transactions(product_id, received_at DESC);

CREATE INDEX ix_transactions_processing_received
    ON core.transactions(processing_status, received_at);

CREATE INDEX ix_transactions_financial_received
    ON core.transactions(financial_status, received_at);

CREATE INDEX ix_transactions_provider_received
    ON core.transactions(actual_provider_id, received_at);

CREATE INDEX ix_transactions_original
    ON core.transactions(original_transaction_id);

CREATE INDEX ix_transactions_response_received
    ON core.transactions(ransys_response_code, received_at);

CREATE TABLE core.transaction_fee_components (
    fee_component_id uuid PRIMARY KEY,
    ransys_transaction_id uuid NOT NULL REFERENCES core.transactions(ransys_transaction_id),
    component_type varchar(64) NOT NULL,
    charged_amount numeric(30,8) NOT NULL,
    accounting_amount numeric(30,8) NOT NULL,
    currency_definition_id uuid NOT NULL REFERENCES core.currency_definitions(currency_definition_id),
    beneficiary_type varchar(32) NOT NULL,
    beneficiary_id uuid NULL,
    refundable boolean NOT NULL DEFAULT false,
    calculation_rule_version bigint NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT ck_fee_component_charged CHECK (charged_amount >= 0),
    CONSTRAINT ck_fee_component_accounting CHECK (accounting_amount >= 0)
);

CREATE INDEX ix_fee_components_tx
    ON core.transaction_fee_components(ransys_transaction_id);

CREATE TABLE core.idempotency_records (
    idempotency_record_id uuid PRIMARY KEY,
    channel_id uuid NOT NULL REFERENCES core.channels(channel_id),
    client_reference varchar(128) NOT NULL,
    idempotency_key varchar(128) NULL,
    fingerprint varchar(128) NOT NULL,
    ransys_transaction_id uuid NOT NULL REFERENCES core.transactions(ransys_transaction_id),
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    expired_at timestamptz NULL,
    CONSTRAINT ck_idempotency_expiry CHECK (expires_at > created_at)
);

CREATE UNIQUE INDEX ux_idempotency_active_reference
    ON core.idempotency_records(channel_id, client_reference)
    WHERE active = true;

CREATE INDEX ix_idempotency_expiry
    ON core.idempotency_records(active, expires_at);

CREATE TABLE core.transaction_attempts (
    transaction_attempt_id uuid PRIMARY KEY,
    ransys_transaction_id uuid NOT NULL REFERENCES core.transactions(ransys_transaction_id),
    attempt_no integer NOT NULL,
    attempt_type varchar(32) NOT NULL,
    provider_id uuid NOT NULL REFERENCES integration.providers(provider_id),
    request_sent boolean NOT NULL DEFAULT false,
    transport_status varchar(32) NOT NULL,
    provider_transaction_status varchar(32) NULL,
    ransys_response_code char(4) NULL,
    provider_response_code varchar(64) NULL,
    provider_response_message varchar(500) NULL,
    provider_reference varchar(128) NULL,
    provider_stan varchar(32) NULL,
    provider_rrn varchar(64) NULL,
    latency_ms integer NULL,
    raw_request_reference varchar(1000) NULL,
    raw_response_reference varchar(1000) NULL,
    correlation_id varchar(128) NOT NULL,
    trace_id varchar(128) NOT NULL,
    provider_sent_at timestamptz NULL,
    provider_response_at timestamptz NULL,
    created_at timestamptz NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_attempt_number UNIQUE (ransys_transaction_id, attempt_no),
    CONSTRAINT ck_attempt_no CHECK (attempt_no > 0),
    CONSTRAINT ck_attempt_latency CHECK (latency_ms IS NULL OR latency_ms >= 0),
    CONSTRAINT ck_attempt_transport_status CHECK (
      transport_status IN ('NOT_SENT','SENT','RESPONSE','TIMEOUT','CONNECTION_ERROR')
    )
);

CREATE INDEX ix_attempts_provider_created
    ON core.transaction_attempts(provider_id, created_at DESC);

CREATE INDEX ix_attempts_provider_reference
    ON core.transaction_attempts(provider_reference);

CREATE INDEX ix_attempts_provider_rrn
    ON core.transaction_attempts(provider_rrn);

CREATE INDEX ix_attempts_transport_created
    ON core.transaction_attempts(transport_status, created_at);

CREATE TABLE core.transaction_state_history (
    history_id uuid PRIMARY KEY,
    ransys_transaction_id uuid NOT NULL REFERENCES core.transactions(ransys_transaction_id),
    transaction_attempt_id uuid NULL REFERENCES core.transaction_attempts(transaction_attempt_id),
    previous_status varchar(32) NULL,
    new_status varchar(32) NOT NULL,
    reason_code varchar(64) NULL,
    reason_description varchar(500) NULL,
    change_source varchar(64) NOT NULL,
    created_at timestamptz NOT NULL
);

CREATE INDEX ix_state_history_tx_created
    ON core.transaction_state_history(ransys_transaction_id, created_at);

-- =========================================================
-- LEDGER
-- =========================================================

CREATE TABLE ledger.wallets (
    wallet_id uuid PRIMARY KEY,
    merchant_id uuid NOT NULL REFERENCES core.merchants(merchant_id),
    product_id uuid NULL REFERENCES core.products(product_id),
    currency_definition_id uuid NOT NULL REFERENCES core.currency_definitions(currency_definition_id),
    ledger_balance numeric(30,8) NOT NULL DEFAULT 0,
    available_balance numeric(30,8) NOT NULL DEFAULT 0,
    reserved_balance numeric(30,8) NOT NULL DEFAULT 0,
    status varchar(32) NOT NULL,
    version_no bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT ck_wallet_ledger_nonnegative CHECK (ledger_balance >= 0),
    CONSTRAINT ck_wallet_available_nonnegative CHECK (available_balance >= 0),
    CONSTRAINT ck_wallet_reserved_nonnegative CHECK (reserved_balance >= 0),
    CONSTRAINT ck_wallet_version CHECK (version_no > 0),
    CONSTRAINT ck_wallet_status CHECK (status IN ('ACTIVE','FROZEN','CLOSED'))
);

CREATE UNIQUE INDEX ux_wallet_main
    ON ledger.wallets(merchant_id, currency_definition_id)
    WHERE product_id IS NULL;

CREATE UNIQUE INDEX ux_wallet_product
    ON ledger.wallets(merchant_id, product_id, currency_definition_id)
    WHERE product_id IS NOT NULL;

CREATE TABLE ledger.balance_reservations (
    reservation_id uuid PRIMARY KEY,
    wallet_id uuid NOT NULL REFERENCES ledger.wallets(wallet_id),
    ransys_transaction_id uuid NOT NULL REFERENCES core.transactions(ransys_transaction_id),
    principal_amount numeric(30,8) NOT NULL,
    fee_amount numeric(30,8) NOT NULL DEFAULT 0,
    total_reserved_amount numeric(30,8) NOT NULL,
    status varchar(32) NOT NULL,
    hold_reason varchar(64) NOT NULL,
    created_at timestamptz NOT NULL,
    committed_at timestamptz NULL,
    released_at timestamptz NULL,
    warning_at timestamptz NULL,
    critical_at timestamptz NULL,
    CONSTRAINT ck_reservation_principal CHECK (principal_amount >= 0),
    CONSTRAINT ck_reservation_fee CHECK (fee_amount >= 0),
    CONSTRAINT ck_reservation_total CHECK (total_reserved_amount = principal_amount + fee_amount),
    CONSTRAINT ck_reservation_status CHECK (status IN ('ACTIVE','COMMITTED','RELEASED'))
);

CREATE UNIQUE INDEX ux_reservation_tx
    ON ledger.balance_reservations(ransys_transaction_id);

CREATE INDEX ix_reservation_active_age
    ON ledger.balance_reservations(created_at)
    WHERE status = 'ACTIVE';

CREATE TABLE ledger.ledger_accounts (
    ledger_account_id uuid PRIMARY KEY,
    account_code varchar(128) NOT NULL UNIQUE,
    account_name varchar(200) NOT NULL,
    owner_type varchar(32) NOT NULL,
    owner_id uuid NULL,
    wallet_id uuid NULL REFERENCES ledger.wallets(wallet_id),
    account_class varchar(32) NOT NULL,
    account_type varchar(64) NOT NULL,
    currency_definition_id uuid NOT NULL REFERENCES core.currency_definitions(currency_definition_id),
    normal_side char(1) NOT NULL,
    status varchar(32) NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT ck_ledger_account_side CHECK (normal_side IN ('D','C')),
    CONSTRAINT ck_ledger_account_class
      CHECK (account_class IN ('ASSET','LIABILITY','REVENUE','EXPENSE','CONTROL')),
    CONSTRAINT ck_ledger_account_status CHECK (status IN ('ACTIVE','CLOSED'))
);

CREATE TABLE ledger.ledger_transactions (
    ledger_transaction_id uuid PRIMARY KEY,
    posting_key varchar(200) NOT NULL UNIQUE,
    ransys_transaction_id uuid NULL REFERENCES core.transactions(ransys_transaction_id),
    reservation_id uuid NULL REFERENCES ledger.balance_reservations(reservation_id),
    approval_request_id uuid NULL,
    operation_type varchar(64) NOT NULL,
    business_reference varchar(128) NOT NULL,
    description varchar(500) NOT NULL,
    status varchar(32) NOT NULL,
    effective_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    created_by_type varchar(32) NOT NULL,
    created_by_id uuid NULL,
    compensates_ledger_transaction_id uuid NULL REFERENCES ledger.ledger_transactions(ledger_transaction_id),
    CONSTRAINT ck_ledger_tx_status CHECK (status IN ('DRAFT','POSTED','REVERSED_BY_COMPENSATION'))
);

CREATE INDEX ix_ledger_tx_ransys
    ON ledger.ledger_transactions(ransys_transaction_id);

CREATE INDEX ix_ledger_tx_effective
    ON ledger.ledger_transactions(effective_at);

CREATE TABLE ledger.ledger_entries (
    ledger_entry_id uuid PRIMARY KEY,
    ledger_transaction_id uuid NOT NULL REFERENCES ledger.ledger_transactions(ledger_transaction_id),
    ledger_account_id uuid NOT NULL REFERENCES ledger.ledger_accounts(ledger_account_id),
    entry_sequence smallint NOT NULL,
    entry_side char(1) NOT NULL,
    amount numeric(30,8) NOT NULL,
    currency_definition_id uuid NOT NULL REFERENCES core.currency_definitions(currency_definition_id),
    created_at timestamptz NOT NULL,
    CONSTRAINT uq_ledger_entry_sequence UNIQUE (ledger_transaction_id, entry_sequence),
    CONSTRAINT ck_ledger_entry_side CHECK (entry_side IN ('D','C')),
    CONSTRAINT ck_ledger_entry_amount CHECK (amount > 0),
    CONSTRAINT ck_ledger_entry_sequence CHECK (entry_sequence > 0)
);

CREATE INDEX ix_ledger_entries_account_created
    ON ledger.ledger_entries(ledger_account_id, created_at);

-- Deferred ledger balance validation.
CREATE OR REPLACE FUNCTION ledger.assert_balanced_journal()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_tx_id uuid;
    v_status varchar(32);
    v_debit numeric(30,8);
    v_credit numeric(30,8);
    v_entry_count integer;
    v_currency_count integer;
BEGIN
    v_tx_id := COALESCE(NEW.ledger_transaction_id, OLD.ledger_transaction_id);

    SELECT status
      INTO v_status
      FROM ledger.ledger_transactions
     WHERE ledger_transaction_id = v_tx_id;

    IF v_status = 'POSTED' THEN
        SELECT
            COALESCE(SUM(CASE WHEN entry_side = 'D' THEN amount ELSE 0 END),0),
            COALESCE(SUM(CASE WHEN entry_side = 'C' THEN amount ELSE 0 END),0),
            COUNT(*),
            COUNT(DISTINCT currency_definition_id)
        INTO v_debit, v_credit, v_entry_count, v_currency_count
        FROM ledger.ledger_entries
        WHERE ledger_transaction_id = v_tx_id;

        IF v_entry_count < 2 THEN
            RAISE EXCEPTION 'Posted ledger transaction % has fewer than two entries', v_tx_id;
        END IF;

        IF v_debit <> v_credit THEN
            RAISE EXCEPTION 'Unbalanced ledger transaction %, debit %, credit %',
                v_tx_id, v_debit, v_credit;
        END IF;

        IF v_currency_count <> 1 THEN
            RAISE EXCEPTION 'Ledger transaction % contains multiple currencies', v_tx_id;
        END IF;
    END IF;

    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_ledger_entries_balanced
AFTER INSERT OR UPDATE OR DELETE ON ledger.ledger_entries
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION ledger.assert_balanced_journal();

-- Check status transition to POSTED even if no entries were inserted in this transaction.
CREATE OR REPLACE FUNCTION ledger.assert_posted_journal()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_debit numeric(30,8);
    v_credit numeric(30,8);
    v_entry_count integer;
    v_currency_count integer;
BEGIN
    IF NEW.status = 'POSTED' THEN
        SELECT
            COALESCE(SUM(CASE WHEN entry_side = 'D' THEN amount ELSE 0 END),0),
            COALESCE(SUM(CASE WHEN entry_side = 'C' THEN amount ELSE 0 END),0),
            COUNT(*),
            COUNT(DISTINCT currency_definition_id)
        INTO v_debit, v_credit, v_entry_count, v_currency_count
        FROM ledger.ledger_entries
        WHERE ledger_transaction_id = NEW.ledger_transaction_id;

        IF v_entry_count < 2 OR v_debit <> v_credit OR v_currency_count <> 1 THEN
            RAISE EXCEPTION 'Cannot post invalid/unbalanced ledger transaction %',
                NEW.ledger_transaction_id;
        END IF;
    END IF;

    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_ledger_tx_posted_valid
AFTER INSERT OR UPDATE OF status ON ledger.ledger_transactions
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION ledger.assert_posted_journal();

-- Immutability protection.
CREATE OR REPLACE FUNCTION ledger.prevent_posted_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_tx_id uuid;
    v_status varchar(32);
BEGIN
    v_tx_id := COALESCE(OLD.ledger_transaction_id, NEW.ledger_transaction_id);

    SELECT status INTO v_status
    FROM ledger.ledger_transactions
    WHERE ledger_transaction_id = v_tx_id;

    IF v_status = 'POSTED' THEN
        RAISE EXCEPTION 'Posted ledger entries are immutable for transaction %', v_tx_id;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_ledger_entries_immutable
BEFORE UPDATE OR DELETE ON ledger.ledger_entries
FOR EACH ROW
EXECUTE FUNCTION ledger.prevent_posted_mutation();

-- =========================================================
-- TOPUP
-- =========================================================

CREATE TABLE core.topup_requests (
    topup_id uuid PRIMARY KEY,
    merchant_id uuid NOT NULL REFERENCES core.merchants(merchant_id),
    wallet_id uuid NOT NULL REFERENCES ledger.wallets(wallet_id),
    topup_reference varchar(128) NOT NULL,
    amount numeric(30,8) NOT NULL,
    currency_definition_id uuid NOT NULL REFERENCES core.currency_definitions(currency_definition_id),
    status varchar(32) NOT NULL,
    external_fund_reference varchar(256) NULL,
    approval_request_id uuid NULL,
    verified_at timestamptz NULL,
    posted_at timestamptz NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT uq_topup_merchant_reference UNIQUE (merchant_id, topup_reference),
    CONSTRAINT ck_topup_amount CHECK (amount > 0),
    CONSTRAINT ck_topup_status CHECK (
      status IN ('DRAFT','PENDING_APPROVAL','APPROVED','VERIFIED','POSTED','REJECTED','FAILED')
    )
);

-- =========================================================
-- PROVIDER INTEGRATION
-- =========================================================

CREATE TABLE integration.provider_endpoints (
    provider_endpoint_id uuid PRIMARY KEY,
    provider_id uuid NOT NULL REFERENCES integration.providers(provider_id),
    environment varchar(32) NOT NULL,
    endpoint_type varchar(32) NOT NULL,
    host_or_url varchar(1000) NOT NULL,
    port integer NULL,
    secret_reference varchar(256) NULL,
    status varchar(32) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT ck_provider_endpoint_port CHECK (port IS NULL OR port BETWEEN 1 AND 65535),
    CONSTRAINT ck_provider_endpoint_status CHECK (status IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE integration.provider_capabilities (
    provider_id uuid NOT NULL REFERENCES integration.providers(provider_id),
    capability_code varchar(64) NOT NULL,
    enabled boolean NOT NULL,
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (provider_id, capability_code)
);

CREATE TABLE integration.provider_transaction_policies (
    policy_id uuid PRIMARY KEY,
    provider_id uuid NOT NULL REFERENCES integration.providers(provider_id),
    product_id uuid NOT NULL REFERENCES core.products(product_id),
    transaction_type varchar(32) NOT NULL,
    connect_timeout_ms integer NOT NULL,
    read_timeout_ms integer NOT NULL,
    max_retry smallint NOT NULL DEFAULT 0,
    retry_delay_ms integer NOT NULL DEFAULT 0,
    retry_backoff_type varchar(32) NOT NULL,
    status_check_after_timeout boolean NOT NULL,
    reversal_after_timeout boolean NOT NULL,
    max_concurrent_requests integer NULL,
    max_queue_depth integer NULL,
    rate_limit_per_second integer NULL,
    effective_from timestamptz NOT NULL,
    effective_until timestamptz NULL,
    version_no bigint NOT NULL,
    CONSTRAINT ck_policy_connect_timeout CHECK (connect_timeout_ms > 0),
    CONSTRAINT ck_policy_read_timeout CHECK (read_timeout_ms > 0),
    CONSTRAINT ck_policy_retry CHECK (max_retry >= 0),
    CONSTRAINT ck_policy_effective_range CHECK (effective_until IS NULL OR effective_until > effective_from)
);

CREATE INDEX ix_provider_policy_lookup
    ON integration.provider_transaction_policies(provider_id, product_id, transaction_type, effective_from DESC);

CREATE TABLE integration.provider_response_mappings (
    mapping_id uuid PRIMARY KEY,
    provider_id uuid NOT NULL REFERENCES integration.providers(provider_id),
    transaction_type varchar(32) NULL,
    provider_response_code varchar(64) NOT NULL,
    ransys_response_code char(4) NOT NULL,
    normalized_status varchar(32) NOT NULL,
    description varchar(500) NULL,
    config_version_id uuid NOT NULL REFERENCES config.config_versions(config_version_id),
    effective_from timestamptz NOT NULL,
    effective_until timestamptz NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT ck_response_mapping_range CHECK (effective_until IS NULL OR effective_until > effective_from)
);

CREATE INDEX ix_response_mapping_lookup
    ON integration.provider_response_mappings(provider_id, provider_response_code, effective_from DESC);

CREATE TABLE integration.provider_operational_state (
    provider_id uuid PRIMARY KEY REFERENCES integration.providers(provider_id),
    manual_enabled boolean NOT NULL DEFAULT true,
    manual_disable_reason varchar(500) NULL,
    manual_disabled_until timestamptz NULL,
    health_state varchar(32) NOT NULL,
    circuit_state varchar(32) NOT NULL,
    state_changed_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT ck_provider_health_state CHECK (health_state IN ('HEALTHY','DEGRADED','UNHEALTHY')),
    CONSTRAINT ck_provider_circuit_state CHECK (circuit_state IN ('CLOSED','OPEN','HALF_OPEN'))
);

-- =========================================================
-- ROUTING / FEE CONFIG
-- =========================================================

CREATE TABLE config.routing_routes (
    routing_route_id uuid PRIMARY KEY,
    config_version_id uuid NOT NULL REFERENCES config.config_versions(config_version_id),
    product_id uuid NOT NULL REFERENCES core.products(product_id),
    transaction_type varchar(32) NULL,
    provider_id uuid NOT NULL REFERENCES integration.providers(provider_id),
    priority smallint NOT NULL,
    enabled boolean NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT ck_routing_priority CHECK (priority > 0)
);

CREATE UNIQUE INDEX ux_routing_priority
    ON config.routing_routes(
        config_version_id,
        product_id,
        COALESCE(transaction_type, '*'),
        priority
    );

CREATE UNIQUE INDEX ux_routing_provider
    ON config.routing_routes(
        config_version_id,
        product_id,
        COALESCE(transaction_type, '*'),
        provider_id
    );

CREATE TABLE config.fee_rules (
    fee_rule_id uuid PRIMARY KEY,
    config_version_id uuid NOT NULL REFERENCES config.config_versions(config_version_id),
    merchant_id uuid NULL REFERENCES core.merchants(merchant_id),
    product_id uuid NOT NULL REFERENCES core.products(product_id),
    transaction_type varchar(32) NOT NULL,
    fee_type varchar(32) NOT NULL,
    fee_value numeric(30,12) NOT NULL,
    minimum_fee numeric(30,8) NULL,
    maximum_fee numeric(30,8) NULL,
    currency_definition_id uuid NOT NULL REFERENCES core.currency_definitions(currency_definition_id),
    effective_from timestamptz NOT NULL,
    effective_until timestamptz NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT ck_fee_type CHECK (fee_type IN ('FIXED','PERCENTAGE')),
    CONSTRAINT ck_fee_value_nonnegative CHECK (fee_value >= 0),
    CONSTRAINT ck_fee_min_nonnegative CHECK (minimum_fee IS NULL OR minimum_fee >= 0),
    CONSTRAINT ck_fee_max_nonnegative CHECK (maximum_fee IS NULL OR maximum_fee >= 0),
    CONSTRAINT ck_fee_min_max CHECK (
      minimum_fee IS NULL OR maximum_fee IS NULL OR maximum_fee >= minimum_fee
    ),
    CONSTRAINT ck_fee_effective_range CHECK (effective_until IS NULL OR effective_until > effective_from)
);

CREATE INDEX ix_fee_rule_lookup
    ON config.fee_rules(product_id, transaction_type, merchant_id, effective_from DESC);

-- =========================================================
-- OUTBOX
-- =========================================================

CREATE TABLE async.outbox_events (
    event_id uuid PRIMARY KEY,
    aggregate_type varchar(64) NOT NULL,
    aggregate_id uuid NOT NULL,
    event_type varchar(128) NOT NULL,
    event_version integer NOT NULL,
    source_version bigint NULL,
    payload jsonb NOT NULL,
    status varchar(32) NOT NULL,
    retry_count integer NOT NULL DEFAULT 0,
    next_retry_at timestamptz NULL,
    locked_by varchar(128) NULL,
    locked_at timestamptz NULL,
    created_at timestamptz NOT NULL,
    published_at timestamptz NULL,
    CONSTRAINT ck_outbox_retry CHECK (retry_count >= 0),
    CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING','PROCESSING','PUBLISHED','DEAD'))
);

CREATE INDEX ix_outbox_worker
    ON async.outbox_events(status, next_retry_at, created_at);

CREATE TABLE async.outbox_delivery_attempts (
    delivery_attempt_id uuid PRIMARY KEY,
    event_id uuid NOT NULL REFERENCES async.outbox_events(event_id),
    attempt_no integer NOT NULL,
    transport varchar(32) NOT NULL,
    result varchar(32) NOT NULL,
    error_code varchar(64) NULL,
    error_message varchar(1000) NULL,
    started_at timestamptz NOT NULL,
    completed_at timestamptz NULL,
    CONSTRAINT uq_outbox_attempt UNIQUE (event_id, attempt_no),
    CONSTRAINT ck_outbox_attempt_no CHECK (attempt_no > 0),
    CONSTRAINT ck_outbox_attempt_result CHECK (result IN ('SUCCESS','FAILED'))
);

-- =========================================================
-- NOTE:
-- Backoffice DB DDL is intentionally a separate deployment/migration
-- because Transaction DB and Backoffice DB are separate physical databases.
-- See RANSYS ERD v1.1 design document for the Backoffice schemas.
-- =========================================================
